package org.medtroniclabs.uhis.common

enum class FilterEnum(val title: String) {
    TODAY("TODAY"),
    YESTERDAY("YESTERDAY"),
    TOMORROW("TOMORROW"),
    ENROLLED("ENROLLED"),
    NOT_ENROLLED("NOT_ENROLLED"),
    HIGH("high"),
    MEDIUM("medium"),
    NORMAL("normal"),
    LOW("low"),
    DAILY("daily"),
    WEEKLY("weekly"),
    MONTHLY("monthly"),
    CUSTOMISE("CUSTOMISE"),
    HYPERTENSION("hypertension"),
    DIABETES("diabetes"),
    BOTH("both"),
    WEEK("WEEK"),
    CC("CC"),
    UHC("UHC"),
    MONTH("MONTH"),
    SUCCESSFUL("SUCCESSFUL"),
    UN_SUCCESSFUL("UN_SUCCESSFUL"),
    CONTROLLED("controlled"),
    UN_CONTROLLED("uncontrolled"),
    RED_RISK("redRisk"),
    VERY_LOW("veryLow"),
    LOW_SMALL("low"),
    MODERATE("moderate"),
    HIGH_SMALL("high"),
    VERY_HIGH("veryHigh"),
}
