package org.medtroniclabs.uhis.ui.dashboard.ncd

object DashboardConstants {
    const val EXTRA_DASHBOARD_SS_IDS = "dashboard_ss_ids"
    const val EXTRA_DASHBOARD_SUB_VILLAGE_IDS = "dashboard_sub_village_ids"
    const val EXTRA_DASHBOARD_STATIC_FILTER = "dashboard_static_filter"

    const val CARD_FAMILY_PLANNING = "family_planning"
    const val CARD_PREGNANT_WOMEN_REGISTRATION = "pregnant_women_registration"
    const val CARD_PREGNANCY_OUTCOME = "pregnancy_outcome"
    const val CARD_ANC = "anc"
    const val CARD_PW_IDENTIFIED_4_MONTHS_ANC = "pw_identified_first4months_anc"
    const val CARD_ANC_3_PLUS = "anc_3_plus"
    const val CARD_HIGH_RISK_PREGNANT_WOMEN = "high_risk_pregnant_women"
    const val CARD_PNC = "pnc"
    const val CARD_CHILD_VISIT = "child_visit"
    const val CARD_HOUSEHOLD_REGISTERED = "household_registered"
    const val CARD_TB_ASSESSMENT = "tb_assessment"
    const val CARD_TB_CONTACT_TRACING = "tb_contact_tracing"
    const val CARD_EYE_CARE = "eye_care"
    const val CARD_CATARACT = "cataract"
    const val CARD_SCREENED = "screened"
    const val CARD_REFERRED = "referred"
    const val CARD_REGISTERED = "registered"
    const val CARD_ASSESSED = "assessed"
    const val CARD_DISPENSED = "dispensed"
    const val CARD_INVESTIGATED = "investigated"
    const val CARD_LIFESTYLE = "lifestyle"
    const val CARD_PSYCHOLOGICAL = "psychological"

    const val CARD_NCD_SCREENING = "ncd_screening_first_service"
    const val CARD_NCD_REFERRED_FOLLOWUP = "ncd_referred_followup"
    const val CARD_NCD_FOLLOW_UP_ASSESSMENT = "ncd_follow_up_assessment"
    const val CARD_TOTAL_NCD_SERVICES = "total_ncd_services"
    const val CARD_TOTAL_EYE_SCREENING = "total_eye_screening"
    const val CARD_CATARACT_SCREENING = "cataract_screening"
    const val CARD_NCD_IN_CATARACT_CAMP = "ncd_in_cataract_camp"
    const val CARD_REFERRED_FOR_OPERATION = "referred_for_operation"
    const val CARD_GLASSES_SOLD = "glasses_sold"
}
